project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "CE_simulation"
  site-url: "https://nikolas-claussen.github.io/CE_simulation"
  description: "discrete simulation of excitable tension+isogonal modes model of convergent extension through intercalations"
  twitter-card: true
  open-graph: true
  repo-branch: master
  repo-url: "https://github.com/nikolas-claussen/CE_simulation"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/nikolas-claussen/CE_simulation"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
