# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/CE_simulation',
                'doc_host': 'https://nikolas-claussen.github.io',
                'git_url': 'https://github.com/nikolas-claussen/CE_simulation',
                'lib_path': 'CE_simulation'},
  'syms': {'CE_simulation.core': {'CE_simulation.core.foo': ('core.html#foo', 'CE_simulation/core.py')}}}