# AUTOGENERATED! DO NOT EDIT! File to edit: ../04_boundary_conditions.ipynb.

# %% auto 0
__all__ = []

# %% ../04_boundary_conditions.ipynb 3
from .triangle import *
from .tension import *
from .delaunay import *
from .isogonal import *

# %% ../04_boundary_conditions.ipynb 4
import os
import sys
import importlib

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

from numpy import sin, cos, tan, pi, sqrt, arccos, arctan, arctan2
from numpy.linalg import norm

from scipy.integrate import solve_ivp
from scipy import ndimage
from scipy import spatial
from scipy import optimize

from tqdm.notebook import tqdm

from copy import deepcopy

from collections import Counter

# %% ../04_boundary_conditions.ipynb 5
from dataclasses import dataclass
from typing import Union, Dict, List, Tuple, Iterable, Callable
from nptyping import NDArray, Int, Float, Shape

from fastcore.foundation import patch

# %% ../04_boundary_conditions.ipynb 6
import ipywidgets as widgets
from matplotlib import animation, rc

# %% ../04_boundary_conditions.ipynb 7
import autograd.numpy as anp  # Thinly-wrapped numpy
from autograd import grad as agrad
