# AUTOGENERATED! DO NOT EDIT! File to edit: ../04c_boundary_conditions_finalize.ipynb.

# %% auto 0
__all__ = []

# %% ../04c_boundary_conditions_finalize.ipynb 3
from .triangle import *
from .tension import *
from .delaunay import *
from .isogonal import *

# %% ../04c_boundary_conditions_finalize.ipynb 4
import os
import sys
import importlib

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib.collections import LineCollection

from numpy import sin, cos, tan, pi, sqrt, arccos, arctan, arctan2
from numpy.linalg import norm

from scipy.integrate import solve_ivp
from scipy import ndimage
from scipy import spatial
from scipy import optimize
from scipy import linalg

from tqdm.notebook import tqdm

from copy import deepcopy
import pickle

from collections import Counter, defaultdict

# %% ../04c_boundary_conditions_finalize.ipynb 5
from dataclasses import dataclass
from typing import Union, Dict, List, Tuple, Iterable, Callable
from nptyping import NDArray, Int, Float, Shape

from fastcore.foundation import patch

# %% ../04c_boundary_conditions_finalize.ipynb 6
import ipywidgets as widgets
from matplotlib import animation, rc

# %% ../04c_boundary_conditions_finalize.ipynb 7
import jax.numpy as jnp
from jax import grad as jgrad
from jax import jit
from jax.tree_util import Partial
from jax.config import config
from jax.nn import relu as jrelu

config.update("jax_enable_x64", True) # 32 bit leads the optimizer to complain about precision loss
#config.update("jax_debug_nans", True)  # useful for debugging, but makes code slower!
